### PR TITLE
New localization helper function New-NotImplementedException

### PR DESCRIPTION
**Pull request by johlju**
#### Pull Request (PR) description
- Changes 2019-04-26
  - Added a new localization helper function 'New-NotImplementedException'.
  - Renamed the tests file for the module DscResource.Common which had the
    wrong name, it is correctly named DscResource.Common.Tests.ps1 now.

*If this PR is approved I will update the style guideline with this new helper function as well*.

#### This Pull Request (PR) fixes the following issues
n/a

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the TEMPLATE_README.md.
      Entry should say what was changed, and how that affects users (if applicable).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresource.template/20)

### CODE REVIEW

**Comment by johlju** [comment]
@PlagueHO @gaelcolas If you have a minute over, look through this if this a good addition. If this PR is approved I will update the style guideline with this new helper function as well.

**Review by PlagueHO — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.template/20)* status: all files reviewed, 2 unresolved discussions (waiting on @johlju)

___
*[Tests/Unit/DscResource.LocalizationHelper.Tests.ps1, line 175 at r1](https://reviewable.io/reviews/powershell/dscresource.template/20#-Le0ccIvEjHbbSaOBX6Q:-Le0ccIw5WsAW7RLv-u6:b-hbiw39) ([raw file](https://github.com/powershell/dscresource.template/blob/da65c97c1fb3d5ccd0a46daa1582392b7c66c853/Tests/Unit/DscResource.LocalizationHelper.Tests.ps1#L175)):*
> ```PowerShell
> 
>     Describe 'DscResource.LocalizationHelper\New-NotImplementedException' {
>         Context 'When calling with Message parameter only' {
> ```

calling -> called
___
*[Tests/Unit/DscResource.LocalizationHelper.Tests.ps1, line 183 at r1](https://reviewable.io/reviews/powershell/dscresource.template/20#-Le0cdj1D3OMfCWepxB8:-Le0cdj1D3OMfCWepxB9:b-hbiw39) ([raw file](https://github.com/powershell/dscresource.template/blob/da65c97c1fb3d5ccd0a46daa1582392b7c66c853/Tests/Unit/DscResource.LocalizationHelper.Tests.ps1#L183)):*
> ```PowerShell
>         }
> 
>         Context 'When calling with both the Message and ErrorRecord parameter' {
> ```

calling -> called

**Review by johlju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.template/20)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @PlagueHO)

___
*[Tests/Unit/DscResource.LocalizationHelper.Tests.ps1, line 175 at r1](https://reviewable.io/reviews/powershell/dscresource.template/20#-Le0ccIvEjHbbSaOBX6Q:-Le0n7WU9BaDp_jbu3kI:b-896fix) ([raw file](https://github.com/powershell/dscresource.template/blob/da65c97c1fb3d5ccd0a46daa1582392b7c66c853/Tests/Unit/DscResource.LocalizationHelper.Tests.ps1#L175)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

calling -> called
</blockquote></details>

Done.
___
*[Tests/Unit/DscResource.LocalizationHelper.Tests.ps1, line 183 at r1](https://reviewable.io/reviews/powershell/dscresource.template/20#-Le0cdj1D3OMfCWepxB8:-Le0n8-Q5QYi8lfvjzGu:b-896fix) ([raw file](https://github.com/powershell/dscresource.template/blob/da65c97c1fb3d5ccd0a46daa1582392b7c66c853/Tests/Unit/DscResource.LocalizationHelper.Tests.ps1#L183)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

calling -> called
</blockquote></details>

Done.

**Review by PlagueHO — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.template/20#-:-Le0oDU3E1xoSXlNNDa8:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
